# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install
    - run: npm run build --if-present
    
    - name: upload artifact 
      uses: actions/upload-artifact@v3
      with: 
        name: sirk-artifact
        path: ./pages
        
#   download-artifact:
#      name: Download Artifact to Remote Machine
#      runs-on: self-hosted
#      steps:
#      - name: Download Artifacts
#        uses: actions/download-artifact@v3
#        with:
#          name: sirk-artifact
     
#      - name: Display structure of downloaded files
#        run: ls -R

  deploy:
    name: Deploy ABC-POS
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.FI_LAB_SERVER }}
        username: ${{ secrets.FI_LAB_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.FI_LAB_PORT }}
        script: |
           cd /home/dareomotosho/sir-k
           sudo git pull origin main
           sudo npm install
           sudo npm run build
           
